version: '3.8'

services:

  backend:
    build: .
    command: ["python", "manage.py", "runserver", "localhost:8000"]
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # - DJANGO_SETTINGS_MODULE=avanzatech_blog.settings.local
      - DB_HOST=db
      - DB_PORT=5432
    env_file:
      - .env
    networks:
      customnet:
        ipv4_address: "192.168.0.2"

  db:
    image: postgres:16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      customnet:
        ipv4_address: "192.168.0.1"
  

volumes:
  postgres_data:

networks:
  customnet:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"