# Generated by Django 5.0.3 on 2024-04-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0004_alter_category_name_alter_permission_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Post Permission',
                'verbose_name_plural': 'Post Permissions',
            },
        ),
    ]
