# Generated by Django 5.0.3 on 2024-04-05 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0005_postpermission_postpermission_unique_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpermission',
            name='permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='permission.permission'),
        ),
    ]
