# Generated by Django 5.0.3 on 2024-04-12 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0006_alter_postpermission_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(choices=[('read', 'Read'), ('edit', 'Edit'), ('none', 'None')], default=None, max_length=10, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='postpermission',
            name='permission',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='permission.permission'),
            preserve_default=False,
        ),
    ]
