# Generated by Django 5.0.3 on 2024-04-15 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_user_blogpost_author'),
        ('permission', '0007_alter_permission_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpermission',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverse_post', to='blog.blogpost'),
        ),
    ]
