# Generated by Django 5.0.3 on 2024-06-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogpost_created_at_alter_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_html',
            field=models.TextField(default=None, verbose_name='Html Content'),
        ),
    ]
