# Generated by Django 5.0.3 on 2024-04-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_team_user_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default=None, max_length=50, unique=True, verbose_name='name'),
        ),
    ]
